# Generated by Django 2.2.6 on 2019-12-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191217_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='genero',
        ),
        migrations.AddField(
            model_name='flor',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
