# Generated by Django 2.2.6 on 2019-12-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191217_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='flor',
            name='estado',
            field=models.ForeignKey(on_delete='nombre', to='core.Estado'),
        ),
    ]
