# Generated by Django 2.2.6 on 2019-12-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191217_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
